/*
 ============================================================================
 Module      : Ultrasonic
 Name        : Ultrasonic.c
 Layer       : HAL
 Author      : RASHA_YASSER
 Description : source file for interface the AVR Ultrasonic driver
 Date        : 28/9/2023
 ============================================================================
 */

#include <util/delay.h> /* For the delay functions */
#include "ICU_HW.h"
#include "Ultrasonic.h"
#include "gpio.h"
#include "common_macros.h"

/************************************************************************************************
 *                                Set Global Definitions                                        *
 ************************************************************************************************/

static volatile uint8  g_edgeCount = 0;
static volatile uint16 g_timeHigh = 0;
static volatile uint16 g_distance_cm = 0;
/*
 * Description :
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the
 * GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);

	/* Create configuration structure for ICU driver */
	ICU_ConfigType Icu_Config = {F_CPU_8,RISING};

	/* Initialize both the ICU driver */
	ICU_HW_init(&Icu_Config);

	/* Set the Call back function pointer in the ICU driver */
	ICU_GetCallBack(&Ultrasonic_edgeProcessing);

}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);
	/* Write one on the trigger pin to start the pulse */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);

	_delay_us(15);	/* delay for processing = 10 us */

	/* Write zero on the trigger pin to end the pulse */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}



/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{


		Ultrasonic_Trigger();
		return g_distance_cm;

}


/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		g_distance_cm = g_timeHigh / 57.7;
		g_edgeCount = 0;
		ICU_setEdgeDetectionType(RISING);
	}

}
